//
//  MVMessageRadioStatus.h
//  MAVLink communications protocol built from common.xml
//
//  Created by mavgen_objc.py
//  http://qgroundcontrol.org/mavlink
//

#import "MVMessage.h"

/*!
 Class that represents a RADIO_STATUS Mavlink message.

 @discussion Status generated by radio and injected into MAVLink stream.
 */
@interface MVMessageRadioStatus : MVMessage

- (id)initWithSystemId:(uint8_t)systemId componentId:(uint8_t)componentId rssi:(uint8_t)rssi remrssi:(uint8_t)remrssi txbuf:(uint8_t)txbuf noise:(uint8_t)noise remnoise:(uint8_t)remnoise rxerrors:(uint16_t)rxerrors fixed:(uint16_t)fixed;

//! Local signal strength
- (uint8_t)rssi;

//! Remote signal strength
- (uint8_t)remrssi;

//! Remaining free buffer space in percent.
- (uint8_t)txbuf;

//! Background noise level
- (uint8_t)noise;

//! Remote background noise level
- (uint8_t)remnoise;

//! Receive errors
- (uint16_t)rxerrors;

//! Count of error corrected packets
- (uint16_t)fixed;

@end
